### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by student-daehn-alter-ego** [msu-csc232-fa21/labs#1]
I know you've shared some source code on recursion in class already. Can you make this available here?

**Comment by student-daehn-alter-ego** [comment]
That was more a topic for the lectures channel. A similar repo exists for lectures.

**Comment by student-daehn-alter-ego** [comment]
Opps... I didn't mean to close this issue; I should leave that up to @professordaehn

**Comment by professordaehn** [comment]
For the reasons @student-daehn-alter-ego mentioned, I will indeed close this issue.
